" Name:         Futon
" Description:  Colorless color scheme for Vim inspired by Photon
" Author:       Cinghio Pinghio
" Maintainer:   Cinghio Pinghio
" Website:      https://github.com/cinghiopinghio/futon.vim
" License:      This file is placed in the public domain
" Last Updated: Mon 20 Jan 2020 12:46:57 PM CET

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'futon'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link Repeat Statement
hi! link Conditional Statement
hi! link Exception Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Define PreProc
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262626', '#d70000', '#87af87', '#af8700',
        \ '#5f87d7', '#af87d7', '#d75f00', '#c6c6c6', '#262626', '#d70000',
        \ '#87af87', '#af8700', '#5f87d7', '#af87d7', '#d75f00', '#c6c6c6']
  if has('nvim')
    let g:terminal_color_0 = '#262626'
    let g:terminal_color_1 = '#d70000'
    let g:terminal_color_2 = '#87af87'
    let g:terminal_color_3 = '#af8700'
    let g:terminal_color_4 = '#5f87d7'
    let g:terminal_color_5 = '#af87d7'
    let g:terminal_color_6 = '#d75f00'
    let g:terminal_color_7 = '#c6c6c6'
    let g:terminal_color_8 = '#262626'
    let g:terminal_color_9 = '#d70000'
    let g:terminal_color_10 = '#87af87'
    let g:terminal_color_11 = '#af8700'
    let g:terminal_color_12 = '#5f87d7'
    let g:terminal_color_13 = '#af87d7'
    let g:terminal_color_14 = '#d75f00'
    let g:terminal_color_15 = '#c6c6c6'
  endif
  if get(g:, 'futon_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#af87d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#af87d7 guibg=#303030 guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#767676 guibg=#303030 guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#767676 guibg=#303030 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#303030 guisp=NONE gui=NONE cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor guifg=#c6c6c6 guibg=#af87d7 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#af87d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#767676 guibg=#303030 guisp=NONE gui=italic cterm=italic
  hi DiffAdd guifg=#87af87 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#af8700 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#d70000 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#d75f00 guibg=NONE guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer guifg=#303030 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#d70000 guibg=#c6c6c6 guisp=NONE gui=reverse cterm=reverse
  hi! link ErrorMsg Error
  hi Warning guifg=#af8700 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi! link WarningMsg Warning
  hi IncSearch guifg=#d75f00 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi MatchParen guifg=NONE guibg=#af8700 guisp=NONE gui=bold cterm=bold
  hi Search guifg=#af87d7 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi Directory guifg=#af87d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#b2b2b2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText guifg=#c6c6c6 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu guifg=NONE guibg=#3a3a3a guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#303030 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#af87d7 guibg=#303030 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#d75f00 guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#d75f00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad guifg=#d70000 guibg=NONE guisp=#d70000 gui=undercurl cterm=undercurl
  hi SpellCap guifg=#87af87 guibg=NONE guisp=#d70000 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#5f87d7 guibg=NONE guisp=#d70000 gui=undercurl cterm=undercurl
  hi SpellRare guifg=#af8700 guibg=NONE guisp=#d70000 gui=undercurl cterm=undercurl
  hi! link StatusLine Normal
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit guifg=#303030 guibg=#303030 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#444444 guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#af87d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment guifg=#767676 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi! link Whitespace Comment
  hi! link Identifier Constant
  hi! link Function Identifier
  hi PreProc guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement guifg=#767676 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type guifg=#af87d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo guifg=#d75f00 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump guifg=#af87d7 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  hi NormalMode guifg=#af87d7 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi InsertMode guifg=#87af87 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi ReplaceMode guifg=#d75f00 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi VisualMode guifg=#5f87d7 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi CommandMode guifg=#d70000 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'futon_transp_bg', 0)
    hi Normal ctermfg=251 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=140 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=243 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=243 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=251 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=251 ctermbg=235 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi CursorLineNr ctermfg=140 ctermbg=236 cterm=NONE
    hi FoldColumn ctermfg=243 ctermbg=236 cterm=NONE
    hi LineNr ctermfg=243 ctermbg=236 cterm=NONE
    hi Terminal ctermfg=251 ctermbg=235 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor ctermfg=251 ctermbg=140 cterm=NONE
  hi Conceal ctermfg=140 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=243 ctermbg=236 cterm=italic
  hi DiffAdd ctermfg=108 ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=136 ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=160 ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=166 ctermbg=NONE cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer ctermfg=236 ctermbg=NONE cterm=NONE
  hi Error ctermfg=160 ctermbg=251 cterm=reverse
  hi! link ErrorMsg Error
  hi Warning ctermfg=136 ctermbg=NONE cterm=reverse
  hi! link WarningMsg Warning
  hi IncSearch ctermfg=166 ctermbg=NONE cterm=reverse
  hi MatchParen ctermfg=NONE ctermbg=136 cterm=bold
  hi Search ctermfg=140 ctermbg=NONE cterm=reverse
  hi Directory ctermfg=140 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=251 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=249 ctermbg=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText ctermfg=251 ctermbg=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu ctermfg=NONE ctermbg=237 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=140 ctermbg=236 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=166 cterm=NONE
  hi WildMenu ctermfg=166 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad ctermfg=160 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=108 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=68 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=136 ctermbg=NONE cterm=underline
  hi! link StatusLine Normal
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=236 ctermbg=236 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=238 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=238 cterm=NONE
  hi Constant ctermfg=140 ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment ctermfg=243 ctermbg=NONE cterm=italic
  hi! link Whitespace Comment
  hi! link Identifier Constant
  hi! link Function Identifier
  hi PreProc ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type ctermfg=140 ctermbg=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo ctermfg=166 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump ctermfg=140 ctermbg=NONE cterm=reverse
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  hi NormalMode ctermfg=140 ctermbg=NONE cterm=reverse
  hi InsertMode ctermfg=108 ctermbg=NONE cterm=reverse
  hi ReplaceMode ctermfg=166 ctermbg=NONE cterm=reverse
  hi VisualMode ctermfg=68 ctermbg=NONE cterm=reverse
  hi CommandMode ctermfg=160 ctermbg=NONE cterm=reverse
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi markdownItalic cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'futon_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=DarkMagenta ctermbg=DarkGray cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
    hi LineNr ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor ctermfg=White ctermbg=DarkMagenta cterm=NONE
  hi Conceal ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Folded ctermfg=DarkGray ctermbg=DarkGray cterm=italic
  hi DiffAdd ctermfg=DarkGreen ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=Red ctermbg=NONE cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=White cterm=reverse
  hi! link ErrorMsg Error
  hi Warning ctermfg=DarkYellow ctermbg=NONE cterm=reverse
  hi! link WarningMsg Warning
  hi IncSearch ctermfg=Red ctermbg=NONE cterm=reverse
  hi MatchParen ctermfg=NONE ctermbg=DarkYellow cterm=bold
  hi Search ctermfg=DarkMagenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=LightGrey ctermbg=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText ctermfg=White ctermbg=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=DarkMagenta ctermbg=DarkGray cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Red cterm=NONE
  hi WildMenu ctermfg=Red ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad ctermfg=DarkRed ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=DarkGreen ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=Blue ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkYellow ctermbg=NONE cterm=underline
  hi! link StatusLine Normal
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment ctermfg=DarkGray ctermbg=NONE cterm=italic
  hi! link Whitespace Comment
  hi! link Identifier Constant
  hi! link Function Identifier
  hi PreProc ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo ctermfg=Red ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump ctermfg=DarkMagenta ctermbg=NONE cterm=reverse
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  hi NormalMode ctermfg=DarkMagenta ctermbg=NONE cterm=reverse
  hi InsertMode ctermfg=DarkGreen ctermbg=NONE cterm=reverse
  hi ReplaceMode ctermfg=Red ctermbg=NONE cterm=reverse
  hi VisualMode ctermfg=Blue ctermbg=NONE cterm=reverse
  hi CommandMode ctermfg=DarkRed ctermbg=NONE cterm=reverse
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi markdownItalic cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: bg0    #262626    235 Black
" Color: darkl_1 #303030    236 DarkGray
" Color: darkl_2 #3a3a3a    237 DarkGray
" Color: darkl_3 #444444    238 DarkGray
" Color: darkl_4 #626262    241 DarkGray
" Color: light   #c6c6c6    251 White
" Color: light_1 #b2b2b2    249 LightGrey
" Color: light_2 #a8a8a8    248 LightGrey
" Color: light_3 #9e9e9e    247 LightGrey
" Color: light_4 #8a8a8a    245 LightGrey
" Color: grey    #767676    243 DarkGray
" Color: purple  #af87d7    140 DarkMagenta
" Color: orange  #d75f00    166 Red
" Color: yellow  #af8700    136 DarkYellow
" Color: green   #87af87    108 DarkGreen
" Color: blue    #5f87d7    68  Blue
" Color: red     #d70000    160 DarkRed
" Color:    xdblack   #262626 ~
" Color:    xdred     #af0000 ~
" Color:    xdgreen   #878700 ~
" Color:    xdyellow  #d78700 ~
" Color:    xdblue    #5f87af ~
" Color:    xdmagenta #af5fd7 ~
" Color:    xdcyan    #5f8787 ~
" Color:    xdwhite   #a8a8a8 ~
" Color:    xlblack   #6c6c6c ~
" Color:    xlred     #d75f00 ~
" Color:    xlgreen   #afaf00 ~
" Color:    xlyellow  #ffaf00 ~
" Color:    xlblue    #5fafd7 ~
" Color:    xlmagenta #af87d7 ~
" Color:    xlcyan    #5fafaf ~
" Color:    xlwhite   #eeeeee ~
" Term Colors: bg0 red green yellow blue purple orange light
" Term Colors: bg0 red green yellow blue purple orange light
" vim: et ts=2 sw=2
