" Name:         Futon
" Description:  Colorless color scheme for Vim inspired by Photon
" Author:       Cinghio Pinghio
" Maintainer:   Cinghio Pinghio
" Website:      https://github.com/cinghiopinghio/futon.vim
" License:      This file is placed in the public domain
" Last Updated: 2021-06-22T10:53:05 CEST

" Generated by Colortemplate v2.1.0

hi clear
let g:colors_name = 'futon'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link Conditional Statement
hi! link Exception Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Define PreProc
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#1c1c1c', '#cc3033', '#7c981f', '#d79921', '#5585a8', '#9b73a8', '#59a6a6', '#bebebe', '#404040', '#d8575a', '#9fc228', '#e3ae48', '#769dba', '#b192bc', '#7ab8b8', '#eeeeee']
    if has('nvim')
      let g:terminal_color_0 = '#1c1c1c'
      let g:terminal_color_1 = '#cc3033'
      let g:terminal_color_2 = '#7c981f'
      let g:terminal_color_3 = '#d79921'
      let g:terminal_color_4 = '#5585a8'
      let g:terminal_color_5 = '#9b73a8'
      let g:terminal_color_6 = '#59a6a6'
      let g:terminal_color_7 = '#bebebe'
      let g:terminal_color_8 = '#404040'
      let g:terminal_color_9 = '#d8575a'
      let g:terminal_color_10 = '#9fc228'
      let g:terminal_color_11 = '#e3ae48'
      let g:terminal_color_12 = '#769dba'
      let g:terminal_color_13 = '#b192bc'
      let g:terminal_color_14 = '#7ab8b8'
      let g:terminal_color_15 = '#eeeeee'
    endif
    if get(g:, 'futon_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
      hi CursorLineNr guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
      hi FoldColumn guifg=#767676 guibg=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#eeeeee guibg=#1c1c1c gui=NONE cterm=NONE
      hi CursorLineNr guifg=#9b73a8 guibg=#2e2e2e gui=NONE cterm=NONE
      hi FoldColumn guifg=#767676 guibg=#2e2e2e gui=NONE cterm=NONE
      hi Terminal guifg=#eeeeee guibg=#1c1c1c gui=NONE cterm=NONE
    endif
    hi LineNr guifg=#767676 guibg=#2e2e2e gui=NONE cterm=NONE
    hi ColorColumn guifg=NONE guibg=#2e2e2e gui=NONE cterm=NONE
    hi! link CursorColumn ColorColumn
    hi! link CursorLine ColorColumn
    hi Cursor guifg=#eeeeee guibg=#9b73a8 gui=NONE cterm=NONE
    hi Conceal guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
    hi Folded guifg=#767676 guibg=#2e2e2e gui=italic cterm=italic
    hi DiffAdd guifg=#7c981f guibg=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#d79921 guibg=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#cc3033 guibg=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#d65d0e guibg=NONE gui=bold,reverse cterm=bold,reverse
    hi! link diffAdded DiffAdd
    hi! link diffRemoved DiffDelete
    hi EndOfBuffer guifg=#2e2e2e guibg=NONE gui=NONE cterm=NONE
    hi Error guifg=#cc3033 guibg=#eeeeee gui=reverse,undercurl cterm=reverse,undercurl
    hi! link ErrorMsg Error
    hi Warning guifg=#d79921 guibg=NONE gui=reverse,underline cterm=reverse,underline
    hi! link WarningMsg Warning
    hi IncSearch guifg=#d65d0e guibg=NONE gui=standout cterm=reverse
    hi MatchParen guifg=#eeeeee guibg=#767676 gui=underline cterm=underline
    hi Search guifg=#9b73a8 guibg=NONE gui=reverse cterm=reverse
    hi Directory guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
    hi ModeMsg guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#d6d6d6 guibg=NONE gui=NONE cterm=NONE
    hi! link Question MoreMsg
    hi NonText guifg=#767676 guibg=NONE gui=NONE cterm=NONE
    hi! link Ignore NonText
    hi Pmenu guifg=#d6d6d6 guibg=#404040 gui=NONE cterm=NONE
    hi PmenuSbar guifg=#d6d6d6 guibg=#2e2e2e gui=NONE cterm=NONE
    hi PmenuSel guifg=#eeeeee guibg=#9b73a8 gui=NONE cterm=NONE
    hi PmenuThumb guifg=NONE guibg=#d65d0e gui=NONE cterm=NONE
    hi WildMenu guifg=#d65d0e guibg=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=#767676 guibg=#2e2e2e gui=NONE cterm=NONE
    hi! link SpecialKey SignColumn
    hi SpellBad guifg=#cc3033 guibg=#2e2e2e guisp=#cc3033 gui=undercurl cterm=underline
    hi SpellCap guifg=#7c981f guibg=#2e2e2e guisp=#cc3033 gui=undercurl cterm=underline
    hi SpellLocal guifg=#5585a8 guibg=#2e2e2e guisp=#cc3033 gui=undercurl cterm=underline
    hi SpellRare guifg=#d79921 guibg=#2e2e2e guisp=#cc3033 gui=undercurl cterm=underline
    hi StatusLine guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    hi! link StatusLineNC Comment
    hi! link TabLine StatusLineNC
    hi! link TabLineFill StatusLineNC
    hi! link TabLineSel StatusLine
    hi Title guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi VertSplit guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#525252 gui=NONE cterm=NONE
    hi VisualNOS guifg=NONE guibg=#525252 gui=NONE cterm=NONE
    hi Constant guifg=#b192bc guibg=NONE gui=NONE cterm=NONE
    hi! link Boolean Constant
    hi! link Character Constant
    hi! link Number Constant
    hi! link Float Number
    hi! link String Constant
    hi Special guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi! link SpecialChar Special
    hi! link SpecialComment Special
    hi! link Delimiter Special
    hi! link Debug Special
    hi Comment guifg=#767676 guibg=NONE gui=italic cterm=italic
    hi! link Whitespace Comment
    hi Identifier guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
    hi! link Function Identifier
    hi PreProc guifg=#767676 guibg=NONE gui=NONE cterm=NONE
    hi! link Include PreProc
    hi Statement guifg=#767676 guibg=NONE gui=NONE cterm=NONE
    hi! link Label Statement
    hi! link Keyword Statement
    hi! link Operator Statement
    hi Type guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
    hi! link StorageClass Type
    hi! link Structure Type
    hi Todo guifg=#d65d0e guibg=NONE gui=bold cterm=bold
    hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
    hi helpHyperTextJump guifg=#9b73a8 guibg=NONE gui=underline cterm=underline
    hi NormalMode guifg=#9b73a8 guibg=NONE gui=reverse cterm=reverse
    hi InsertMode guifg=#7c981f guibg=NONE gui=reverse cterm=reverse
    hi ReplaceMode guifg=#d65d0e guibg=NONE gui=reverse cterm=reverse
    hi VisualMode guifg=#5585a8 guibg=NONE gui=reverse cterm=reverse
    hi CommandMode guifg=#cc3033 guibg=NONE gui=reverse cterm=reverse
    hi! link NormalFloat Pmenu
    hi! link FloatBorder Normal
    hi NormalNC guifg=#a6a6a6 guibg=NONE gui=NONE cterm=NONE
    hi! link Floaterm ColorColumn
    hi! link FloatermBorder Folded
    hi markdownBold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link markdownError Error
    hi texItalStyle guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link LspDiagnosticsDefaultError Error
    hi! link LspDiagnosticsDefaultTextError Error
    hi! link LspDiagnosticsDefaultWarning Warning
    hi LspDiagnosticsDefaultInformation guifg=#d6d6d6 guibg=#2e2e2e gui=NONE cterm=NONE
    hi LspDiagnosticsDefaultHint guifg=#a6a6a6 guibg=#2e2e2e gui=NONE cterm=NONE
    hi LspDiagnosticsFloatingError guifg=#cc3033 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsFloatingWarning guifg=#d79921 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsFloatingInformation guifg=#d6d6d6 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsFloatingHint guifg=#a6a6a6 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextError guifg=#cc3033 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextWarning guifg=#d79921 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextInformation guifg=#d6d6d6 guibg=NONE gui=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextHint guifg=#a6a6a6 guibg=NONE gui=NONE cterm=NONE
    hi! link TSConstant Constant
    hi! link TSConstBuiltin Constant
    hi! link TSConstMacro Constant
    hi! link TSNumber Number
    hi! link TSFloat Float
    hi! link TSBoolean Boolean
    hi! link TSCharacter Character
    hi! link TSString String
    hi! link TSStringRegex String
    hi! link TSStringEscape String
    hi TSVariable guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
    hi TSFunction guifg=#d79921 guibg=NONE gui=bold cterm=bold
    hi! link TSClass TSFunction
    hi TSMethod guifg=#d6d6d6 guibg=NONE gui=bold cterm=bold
    hi! link TSField TSMethod
    hi TSOperator guifg=#a6a6a6 guibg=NONE gui=bold cterm=bold
    hi TSLabel guifg=#a6a6a6 guibg=NONE gui=bold,italic cterm=bold,italic
    hi! link TSRepeat TSLabel
    hi! link TSConditional TSLabel
    hi! link TSKeyword TSLabel
    hi! link TSKeywordOperator TSLabel
    hi! link TSVariableBuiltin TSLabel
    hi TSConstructor guifg=#7ab8b8 guibg=NONE gui=NONE cterm=NONE
    hi! link TSPunctDelimeter Delimiter
    hi! link TSPunctBracket Delimiter
    hi pythonStatement guifg=#b192bc guibg=NONE gui=bold cterm=bold
    hi! link pythonRepeat pythonStatement
    hi! link pythonConditional pythonStatement
    hi! link pythonException pythonStatement
    hi pythonClass guifg=#d79921 guibg=NONE gui=bold cterm=bold
    hi! link pythonFunction pythonClass
    hi pythonOperator guifg=#eeeeee guibg=NONE gui=bold cterm=bold
    hi pythonTodo guifg=NONE guibg=#cc3033 gui=bold cterm=bold
    hi! link htmlTag Constant
    hi! link htmlTagName htmlTag
    hi! link htmlEndTag htmlTag
    hi! link htmlSpecialTagName htmlTag
    hi! link gitcommitSummary Title
    if !s:italics
      hi Folded gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
      hi markdownItalic gui=NONE cterm=NONE
      hi texItalStyle gui=NONE cterm=NONE
      hi TSLabel gui=bold cterm=bold
    endif
    if has('nvim')
      hi! link TermCursor Cursor
      hi! link TermCursorNC CursorColumn
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#eeeeee', '#cc3033', '#7c981f', '#d79921', '#5585a8', '#9b73a8', '#d65d0e', '#404040', '#bebebe', '#d8575a', '#9fc228', '#e3ae48', '#769dba', '#b192bc', '#7ab8b8', '#1c1c1c']
  if has('nvim')
    let g:terminal_color_0 = '#eeeeee'
    let g:terminal_color_1 = '#cc3033'
    let g:terminal_color_2 = '#7c981f'
    let g:terminal_color_3 = '#d79921'
    let g:terminal_color_4 = '#5585a8'
    let g:terminal_color_5 = '#9b73a8'
    let g:terminal_color_6 = '#d65d0e'
    let g:terminal_color_7 = '#404040'
    let g:terminal_color_8 = '#bebebe'
    let g:terminal_color_9 = '#d8575a'
    let g:terminal_color_10 = '#9fc228'
    let g:terminal_color_11 = '#e3ae48'
    let g:terminal_color_12 = '#769dba'
    let g:terminal_color_13 = '#b192bc'
    let g:terminal_color_14 = '#7ab8b8'
    let g:terminal_color_15 = '#1c1c1c'
  endif
  if get(g:, 'futon_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#767676 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#1c1c1c guibg=#eeeeee gui=NONE cterm=NONE
    hi CursorLineNr guifg=#9b73a8 guibg=#d6d6d6 gui=NONE cterm=NONE
    hi FoldColumn guifg=#767676 guibg=#d6d6d6 gui=NONE cterm=NONE
    hi Terminal guifg=#1c1c1c guibg=#eeeeee gui=NONE cterm=NONE
  endif
  hi LineNr guifg=#767676 guibg=#d6d6d6 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#d6d6d6 gui=NONE cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor guifg=#1c1c1c guibg=#9b73a8 gui=NONE cterm=NONE
  hi Conceal guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
  hi Folded guifg=#767676 guibg=#d6d6d6 gui=italic cterm=italic
  hi DiffAdd guifg=#7c981f guibg=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#d79921 guibg=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#cc3033 guibg=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#d65d0e guibg=NONE gui=bold,reverse cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer guifg=#d6d6d6 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#cc3033 guibg=#1c1c1c gui=reverse,undercurl cterm=reverse,undercurl
  hi! link ErrorMsg Error
  hi Warning guifg=#d79921 guibg=NONE gui=reverse,underline cterm=reverse,underline
  hi! link WarningMsg Warning
  hi IncSearch guifg=#d65d0e guibg=NONE gui=standout cterm=reverse
  hi MatchParen guifg=#1c1c1c guibg=#767676 gui=underline cterm=underline
  hi Search guifg=#9b73a8 guibg=NONE gui=reverse cterm=reverse
  hi Directory guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#2e2e2e guibg=NONE gui=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText guifg=#767676 guibg=NONE gui=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu guifg=#2e2e2e guibg=#bebebe gui=NONE cterm=NONE
  hi PmenuSbar guifg=#2e2e2e guibg=#d6d6d6 gui=NONE cterm=NONE
  hi PmenuSel guifg=#1c1c1c guibg=#9b73a8 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#d65d0e gui=NONE cterm=NONE
  hi WildMenu guifg=#d65d0e guibg=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#767676 guibg=#d6d6d6 gui=NONE cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad guifg=#cc3033 guibg=#d6d6d6 guisp=#cc3033 gui=undercurl cterm=underline
  hi SpellCap guifg=#7c981f guibg=#d6d6d6 guisp=#cc3033 gui=undercurl cterm=underline
  hi SpellLocal guifg=#5585a8 guibg=#d6d6d6 guisp=#cc3033 gui=undercurl cterm=underline
  hi SpellRare guifg=#d79921 guibg=#d6d6d6 guisp=#cc3033 gui=undercurl cterm=underline
  hi StatusLine guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit guifg=#eeeeee guibg=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#a6a6a6 gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#a6a6a6 gui=NONE cterm=NONE
  hi Constant guifg=#82598f guibg=NONE gui=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment guifg=#767676 guibg=NONE gui=italic cterm=italic
  hi! link Whitespace Comment
  hi Identifier guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
  hi! link Function Identifier
  hi PreProc guifg=#767676 guibg=NONE gui=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement guifg=#767676 guibg=NONE gui=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type guifg=#9b73a8 guibg=NONE gui=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo guifg=#d65d0e guibg=NONE gui=bold cterm=bold
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump guifg=#9b73a8 guibg=NONE gui=underline cterm=underline
  hi NormalMode guifg=#9b73a8 guibg=NONE gui=reverse cterm=reverse
  hi InsertMode guifg=#7c981f guibg=NONE gui=reverse cterm=reverse
  hi ReplaceMode guifg=#d65d0e guibg=NONE gui=reverse cterm=reverse
  hi VisualMode guifg=#5585a8 guibg=NONE gui=reverse cterm=reverse
  hi CommandMode guifg=#cc3033 guibg=NONE gui=reverse cterm=reverse
  hi! link NormalFloat Pmenu
  hi! link FloatBorder Normal
  hi NormalNC guifg=#525252 guibg=NONE gui=NONE cterm=NONE
  hi! link Floaterm ColorColumn
  hi! link FloatermBorder Folded
  hi markdownBold guifg=NONE guibg=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  hi texItalStyle guifg=NONE guibg=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link LspDiagnosticsDefaultError Error
  hi! link LspDiagnosticsDefaultTextError Error
  hi! link LspDiagnosticsDefaultWarning Warning
  hi LspDiagnosticsDefaultInformation guifg=#2e2e2e guibg=#d6d6d6 gui=NONE cterm=NONE
  hi LspDiagnosticsDefaultHint guifg=#525252 guibg=#d6d6d6 gui=NONE cterm=NONE
  hi LspDiagnosticsFloatingError guifg=#cc3033 guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsFloatingWarning guifg=#d79921 guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsFloatingInformation guifg=#2e2e2e guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsFloatingHint guifg=#525252 guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextError guifg=#cc3033 guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextWarning guifg=#d79921 guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextInformation guifg=#2e2e2e guibg=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextHint guifg=#525252 guibg=NONE gui=NONE cterm=NONE
  hi! link TSConstant Constant
  hi! link TSConstBuiltin Constant
  hi! link TSConstMacro Constant
  hi! link TSNumber Number
  hi! link TSFloat Float
  hi! link TSBoolean Boolean
  hi! link TSCharacter Character
  hi! link TSString String
  hi! link TSStringRegex String
  hi! link TSStringEscape String
  hi TSVariable guifg=#1c1c1c guibg=NONE gui=NONE cterm=NONE
  hi TSFunction guifg=#d79921 guibg=NONE gui=bold cterm=bold
  hi! link TSClass TSFunction
  hi TSMethod guifg=#2e2e2e guibg=NONE gui=bold cterm=bold
  hi! link TSField TSMethod
  hi TSOperator guifg=#525252 guibg=NONE gui=bold cterm=bold
  hi TSLabel guifg=#525252 guibg=NONE gui=bold,italic cterm=bold,italic
  hi! link TSRepeat TSLabel
  hi! link TSConditional TSLabel
  hi! link TSKeyword TSLabel
  hi! link TSKeywordOperator TSLabel
  hi! link TSVariableBuiltin TSLabel
  hi TSConstructor guifg=#478585 guibg=NONE gui=NONE cterm=NONE
  hi! link TSPunctDelimeter Delimiter
  hi! link TSPunctBracket Delimiter
  hi pythonStatement guifg=#82598f guibg=NONE gui=bold cterm=bold
  hi! link pythonRepeat pythonStatement
  hi! link pythonConditional pythonStatement
  hi! link pythonException pythonStatement
  hi pythonClass guifg=#d79921 guibg=NONE gui=bold cterm=bold
  hi! link pythonFunction pythonClass
  hi pythonOperator guifg=#1c1c1c guibg=NONE gui=bold cterm=bold
  hi pythonTodo guifg=NONE guibg=#cc3033 gui=bold cterm=bold
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
    hi texItalStyle gui=NONE cterm=NONE
    hi TSLabel gui=bold cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'futon_transp_bg', 0)
      hi Normal ctermfg=255 ctermbg=NONE cterm=NONE
      hi CursorLineNr ctermfg=133 ctermbg=NONE cterm=NONE
      hi FoldColumn ctermfg=243 ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=255 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=255 ctermbg=234 cterm=NONE
      if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
        set background=dark
      endif
      hi CursorLineNr ctermfg=133 ctermbg=236 cterm=NONE
      hi FoldColumn ctermfg=243 ctermbg=236 cterm=NONE
      hi Terminal ctermfg=255 ctermbg=234 cterm=NONE
    endif
    hi LineNr ctermfg=243 ctermbg=236 cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi! link CursorColumn ColorColumn
    hi! link CursorLine ColorColumn
    hi Cursor ctermfg=255 ctermbg=133 cterm=NONE
    hi Conceal ctermfg=133 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=243 ctermbg=236 cterm=italic
    hi DiffAdd ctermfg=64 ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=172 ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=160 ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=166 ctermbg=NONE cterm=bold,reverse
    hi! link diffAdded DiffAdd
    hi! link diffRemoved DiffDelete
    hi EndOfBuffer ctermfg=236 ctermbg=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=255 cterm=reverse,undercurl
    hi! link ErrorMsg Error
    hi Warning ctermfg=172 ctermbg=NONE cterm=reverse,underline
    hi! link WarningMsg Warning
    hi IncSearch ctermfg=166 ctermbg=NONE cterm=reverse
    hi MatchParen ctermfg=255 ctermbg=243 cterm=underline
    hi Search ctermfg=133 ctermbg=NONE cterm=reverse
    hi Directory ctermfg=133 ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=255 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=188 ctermbg=NONE cterm=NONE
    hi! link Question MoreMsg
    hi NonText ctermfg=243 ctermbg=NONE cterm=NONE
    hi! link Ignore NonText
    hi Pmenu ctermfg=188 ctermbg=238 cterm=NONE
    hi PmenuSbar ctermfg=188 ctermbg=236 cterm=NONE
    hi PmenuSel ctermfg=255 ctermbg=133 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=166 cterm=NONE
    hi WildMenu ctermfg=166 ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=243 ctermbg=236 cterm=NONE
    hi! link SpecialKey SignColumn
    hi SpellBad ctermfg=160 ctermbg=236 cterm=underline
    hi SpellCap ctermfg=64 ctermbg=236 cterm=underline
    hi SpellLocal ctermfg=67 ctermbg=236 cterm=underline
    hi SpellRare ctermfg=172 ctermbg=236 cterm=underline
    hi StatusLine ctermfg=255 ctermbg=NONE cterm=NONE
    hi! link StatusLineNC Comment
    hi! link TabLine StatusLineNC
    hi! link TabLineFill StatusLineNC
    hi! link TabLineSel StatusLine
    hi Title ctermfg=NONE ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=234 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=239 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=239 cterm=NONE
    hi Constant ctermfg=139 ctermbg=NONE cterm=NONE
    hi! link Boolean Constant
    hi! link Character Constant
    hi! link Number Constant
    hi! link Float Number
    hi! link String Constant
    hi Special ctermfg=NONE ctermbg=NONE cterm=bold
    hi! link SpecialChar Special
    hi! link SpecialComment Special
    hi! link Delimiter Special
    hi! link Debug Special
    hi Comment ctermfg=243 ctermbg=NONE cterm=italic
    hi! link Whitespace Comment
    hi Identifier ctermfg=133 ctermbg=NONE cterm=NONE
    hi! link Function Identifier
    hi PreProc ctermfg=243 ctermbg=NONE cterm=NONE
    hi! link Include PreProc
    hi Statement ctermfg=243 ctermbg=NONE cterm=NONE
    hi! link Label Statement
    hi! link Keyword Statement
    hi! link Operator Statement
    hi Type ctermfg=133 ctermbg=NONE cterm=NONE
    hi! link StorageClass Type
    hi! link Structure Type
    hi Todo ctermfg=166 ctermbg=NONE cterm=bold
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
    hi helpHyperTextJump ctermfg=133 ctermbg=NONE cterm=underline
    hi NormalMode ctermfg=133 ctermbg=NONE cterm=reverse
    hi InsertMode ctermfg=64 ctermbg=NONE cterm=reverse
    hi ReplaceMode ctermfg=166 ctermbg=NONE cterm=reverse
    hi VisualMode ctermfg=67 ctermbg=NONE cterm=reverse
    hi CommandMode ctermfg=160 ctermbg=NONE cterm=reverse
    hi! link NormalFloat Pmenu
    hi! link FloatBorder Normal
    hi NormalNC ctermfg=248 ctermbg=NONE cterm=NONE
    hi! link Floaterm ColorColumn
    hi! link FloatermBorder Folded
    hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link markdownError Error
    hi texItalStyle ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link LspDiagnosticsDefaultError Error
    hi! link LspDiagnosticsDefaultTextError Error
    hi! link LspDiagnosticsDefaultWarning Warning
    hi LspDiagnosticsDefaultInformation ctermfg=188 ctermbg=236 cterm=NONE
    hi LspDiagnosticsDefaultHint ctermfg=248 ctermbg=236 cterm=NONE
    hi LspDiagnosticsFloatingError ctermfg=160 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingWarning ctermfg=172 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingInformation ctermfg=188 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingHint ctermfg=248 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextError ctermfg=160 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextWarning ctermfg=172 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextInformation ctermfg=188 ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextHint ctermfg=248 ctermbg=NONE cterm=NONE
    hi! link TSConstant Constant
    hi! link TSConstBuiltin Constant
    hi! link TSConstMacro Constant
    hi! link TSNumber Number
    hi! link TSFloat Float
    hi! link TSBoolean Boolean
    hi! link TSCharacter Character
    hi! link TSString String
    hi! link TSStringRegex String
    hi! link TSStringEscape String
    hi TSVariable ctermfg=255 ctermbg=NONE cterm=NONE
    hi TSFunction ctermfg=172 ctermbg=NONE cterm=bold
    hi! link TSClass TSFunction
    hi TSMethod ctermfg=188 ctermbg=NONE cterm=bold
    hi! link TSField TSMethod
    hi TSOperator ctermfg=248 ctermbg=NONE cterm=bold
    hi TSLabel ctermfg=248 ctermbg=NONE cterm=bold,italic
    hi! link TSRepeat TSLabel
    hi! link TSConditional TSLabel
    hi! link TSKeyword TSLabel
    hi! link TSKeywordOperator TSLabel
    hi! link TSVariableBuiltin TSLabel
    hi TSConstructor ctermfg=73 ctermbg=NONE cterm=NONE
    hi! link TSPunctDelimeter Delimiter
    hi! link TSPunctBracket Delimiter
    hi pythonStatement ctermfg=139 ctermbg=NONE cterm=bold
    hi! link pythonRepeat pythonStatement
    hi! link pythonConditional pythonStatement
    hi! link pythonException pythonStatement
    hi pythonClass ctermfg=172 ctermbg=NONE cterm=bold
    hi! link pythonFunction pythonClass
    hi pythonOperator ctermfg=255 ctermbg=NONE cterm=bold
    hi pythonTodo ctermfg=NONE ctermbg=160 cterm=bold
    hi! link htmlTag Constant
    hi! link htmlTagName htmlTag
    hi! link htmlEndTag htmlTag
    hi! link htmlSpecialTagName htmlTag
    hi! link gitcommitSummary Title
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
      hi markdownItalic cterm=NONE
      hi texItalStyle cterm=NONE
      hi TSLabel cterm=bold
    endif
    if has('nvim')
      hi! link TermCursor Cursor
      hi! link TermCursorNC CursorColumn
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'futon_transp_bg', 0)
    hi Normal ctermfg=234 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=133 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=243 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=234 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=234 ctermbg=255 cterm=NONE
    hi CursorLineNr ctermfg=133 ctermbg=188 cterm=NONE
    hi FoldColumn ctermfg=243 ctermbg=188 cterm=NONE
    hi Terminal ctermfg=234 ctermbg=255 cterm=NONE
  endif
  hi LineNr ctermfg=243 ctermbg=188 cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=188 cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor ctermfg=234 ctermbg=133 cterm=NONE
  hi Conceal ctermfg=133 ctermbg=NONE cterm=NONE
  hi Folded ctermfg=243 ctermbg=188 cterm=italic
  hi DiffAdd ctermfg=64 ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=172 ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=160 ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=166 ctermbg=NONE cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer ctermfg=188 ctermbg=NONE cterm=NONE
  hi Error ctermfg=160 ctermbg=234 cterm=reverse,undercurl
  hi! link ErrorMsg Error
  hi Warning ctermfg=172 ctermbg=NONE cterm=reverse,underline
  hi! link WarningMsg Warning
  hi IncSearch ctermfg=166 ctermbg=NONE cterm=reverse
  hi MatchParen ctermfg=234 ctermbg=243 cterm=underline
  hi Search ctermfg=133 ctermbg=NONE cterm=reverse
  hi Directory ctermfg=133 ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=234 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=236 ctermbg=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu ctermfg=236 ctermbg=250 cterm=NONE
  hi PmenuSbar ctermfg=236 ctermbg=188 cterm=NONE
  hi PmenuSel ctermfg=234 ctermbg=133 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=166 cterm=NONE
  hi WildMenu ctermfg=166 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=243 ctermbg=188 cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad ctermfg=160 ctermbg=188 cterm=underline
  hi SpellCap ctermfg=64 ctermbg=188 cterm=underline
  hi SpellLocal ctermfg=67 ctermbg=188 cterm=underline
  hi SpellRare ctermfg=172 ctermbg=188 cterm=underline
  hi StatusLine ctermfg=234 ctermbg=NONE cterm=NONE
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=255 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=248 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=248 cterm=NONE
  hi Constant ctermfg=96 ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment ctermfg=243 ctermbg=NONE cterm=italic
  hi! link Whitespace Comment
  hi Identifier ctermfg=133 ctermbg=NONE cterm=NONE
  hi! link Function Identifier
  hi PreProc ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement ctermfg=243 ctermbg=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type ctermfg=133 ctermbg=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo ctermfg=166 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump ctermfg=133 ctermbg=NONE cterm=underline
  hi NormalMode ctermfg=133 ctermbg=NONE cterm=reverse
  hi InsertMode ctermfg=64 ctermbg=NONE cterm=reverse
  hi ReplaceMode ctermfg=166 ctermbg=NONE cterm=reverse
  hi VisualMode ctermfg=67 ctermbg=NONE cterm=reverse
  hi CommandMode ctermfg=160 ctermbg=NONE cterm=reverse
  hi! link NormalFloat Pmenu
  hi! link FloatBorder Normal
  hi NormalNC ctermfg=239 ctermbg=NONE cterm=NONE
  hi! link Floaterm ColorColumn
  hi! link FloatermBorder Folded
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  hi texItalStyle ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link LspDiagnosticsDefaultError Error
  hi! link LspDiagnosticsDefaultTextError Error
  hi! link LspDiagnosticsDefaultWarning Warning
  hi LspDiagnosticsDefaultInformation ctermfg=236 ctermbg=188 cterm=NONE
  hi LspDiagnosticsDefaultHint ctermfg=239 ctermbg=188 cterm=NONE
  hi LspDiagnosticsFloatingError ctermfg=160 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingWarning ctermfg=172 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingInformation ctermfg=236 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingHint ctermfg=239 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextError ctermfg=160 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextWarning ctermfg=172 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextInformation ctermfg=236 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextHint ctermfg=239 ctermbg=NONE cterm=NONE
  hi! link TSConstant Constant
  hi! link TSConstBuiltin Constant
  hi! link TSConstMacro Constant
  hi! link TSNumber Number
  hi! link TSFloat Float
  hi! link TSBoolean Boolean
  hi! link TSCharacter Character
  hi! link TSString String
  hi! link TSStringRegex String
  hi! link TSStringEscape String
  hi TSVariable ctermfg=234 ctermbg=NONE cterm=NONE
  hi TSFunction ctermfg=172 ctermbg=NONE cterm=bold
  hi! link TSClass TSFunction
  hi TSMethod ctermfg=236 ctermbg=NONE cterm=bold
  hi! link TSField TSMethod
  hi TSOperator ctermfg=239 ctermbg=NONE cterm=bold
  hi TSLabel ctermfg=239 ctermbg=NONE cterm=bold,italic
  hi! link TSRepeat TSLabel
  hi! link TSConditional TSLabel
  hi! link TSKeyword TSLabel
  hi! link TSKeywordOperator TSLabel
  hi! link TSVariableBuiltin TSLabel
  hi TSConstructor ctermfg=66 ctermbg=NONE cterm=NONE
  hi! link TSPunctDelimeter Delimiter
  hi! link TSPunctBracket Delimiter
  hi pythonStatement ctermfg=96 ctermbg=NONE cterm=bold
  hi! link pythonRepeat pythonStatement
  hi! link pythonConditional pythonStatement
  hi! link pythonException pythonStatement
  hi pythonClass ctermfg=172 ctermbg=NONE cterm=bold
  hi! link pythonFunction pythonClass
  hi pythonOperator ctermfg=234 ctermbg=NONE cterm=bold
  hi pythonTodo ctermfg=NONE ctermbg=160 cterm=bold
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi markdownItalic cterm=NONE
    hi texItalStyle cterm=NONE
    hi TSLabel cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'futon_transp_bg', 0)
      hi Normal ctermfg=White ctermbg=NONE cterm=NONE
      hi CursorLineNr ctermfg=Magenta ctermbg=NONE cterm=NONE
      hi FoldColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi CursorLineNr ctermfg=Magenta ctermbg=DarkGray cterm=NONE
      hi FoldColumn ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi LineNr ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi! link CursorColumn ColorColumn
    hi! link CursorLine ColorColumn
    hi Cursor ctermfg=White ctermbg=Magenta cterm=NONE
    hi Conceal ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi Folded ctermfg=DarkGray ctermbg=DarkGray cterm=italic
    hi DiffAdd ctermfg=Green ctermbg=NONE cterm=reverse
    hi DiffChange ctermfg=Yellow ctermbg=NONE cterm=reverse
    hi DiffDelete ctermfg=Red ctermbg=NONE cterm=reverse
    hi DiffText ctermfg=Gray ctermbg=NONE cterm=bold,reverse
    hi! link diffAdded DiffAdd
    hi! link diffRemoved DiffDelete
    hi EndOfBuffer ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=reverse,undercurl
    hi! link ErrorMsg Error
    hi Warning ctermfg=Yellow ctermbg=NONE cterm=reverse,underline
    hi! link WarningMsg Warning
    hi IncSearch ctermfg=Gray ctermbg=NONE cterm=reverse
    hi MatchParen ctermfg=White ctermbg=DarkGray cterm=underline
    hi Search ctermfg=Magenta ctermbg=NONE cterm=reverse
    hi Directory ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
    hi! link Question MoreMsg
    hi NonText ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi! link Ignore NonText
    hi Pmenu ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi PmenuSbar ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi PmenuSel ctermfg=White ctermbg=Magenta cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=Gray cterm=NONE
    hi WildMenu ctermfg=Gray ctermbg=NONE cterm=NONE
    hi SignColumn ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
    hi! link SpecialKey SignColumn
    hi SpellBad ctermfg=Red ctermbg=DarkGray cterm=underline
    hi SpellCap ctermfg=Green ctermbg=DarkGray cterm=underline
    hi SpellLocal ctermfg=Blue ctermbg=DarkGray cterm=underline
    hi SpellRare ctermfg=Yellow ctermbg=DarkGray cterm=underline
    hi StatusLine ctermfg=White ctermbg=NONE cterm=NONE
    hi! link StatusLineNC Comment
    hi! link TabLine StatusLineNC
    hi! link TabLineFill StatusLineNC
    hi! link TabLineSel StatusLine
    hi Title ctermfg=NONE ctermbg=NONE cterm=bold
    hi VertSplit ctermfg=Black ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=DarkGray cterm=NONE
    hi Constant ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi! link Boolean Constant
    hi! link Character Constant
    hi! link Number Constant
    hi! link Float Number
    hi! link String Constant
    hi Special ctermfg=NONE ctermbg=NONE cterm=bold
    hi! link SpecialChar Special
    hi! link SpecialComment Special
    hi! link Delimiter Special
    hi! link Debug Special
    hi Comment ctermfg=DarkGray ctermbg=NONE cterm=italic
    hi! link Whitespace Comment
    hi Identifier ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi! link Function Identifier
    hi PreProc ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi! link Include PreProc
    hi Statement ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi! link Label Statement
    hi! link Keyword Statement
    hi! link Operator Statement
    hi Type ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi! link StorageClass Type
    hi! link Structure Type
    hi Todo ctermfg=Gray ctermbg=NONE cterm=bold
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
    hi helpHyperTextJump ctermfg=Magenta ctermbg=NONE cterm=underline
    hi NormalMode ctermfg=Magenta ctermbg=NONE cterm=reverse
    hi InsertMode ctermfg=Green ctermbg=NONE cterm=reverse
    hi ReplaceMode ctermfg=Gray ctermbg=NONE cterm=reverse
    hi VisualMode ctermfg=Blue ctermbg=NONE cterm=reverse
    hi CommandMode ctermfg=Red ctermbg=NONE cterm=reverse
    hi! link NormalFloat Pmenu
    hi! link FloatBorder Normal
    hi NormalNC ctermfg=Gray ctermbg=NONE cterm=NONE
    hi! link Floaterm ColorColumn
    hi! link FloatermBorder Folded
    hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
    hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link markdownError Error
    hi texItalStyle ctermfg=NONE ctermbg=NONE cterm=italic
    hi! link LspDiagnosticsDefaultError Error
    hi! link LspDiagnosticsDefaultTextError Error
    hi! link LspDiagnosticsDefaultWarning Warning
    hi LspDiagnosticsDefaultInformation ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi LspDiagnosticsDefaultHint ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi LspDiagnosticsFloatingError ctermfg=Red ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingWarning ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingInformation ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LspDiagnosticsFloatingHint ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextError ctermfg=Red ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextWarning ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextInformation ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LspDiagnosticsVirtualTextHint ctermfg=Gray ctermbg=NONE cterm=NONE
    hi! link TSConstant Constant
    hi! link TSConstBuiltin Constant
    hi! link TSConstMacro Constant
    hi! link TSNumber Number
    hi! link TSFloat Float
    hi! link TSBoolean Boolean
    hi! link TSCharacter Character
    hi! link TSString String
    hi! link TSStringRegex String
    hi! link TSStringEscape String
    hi TSVariable ctermfg=White ctermbg=NONE cterm=NONE
    hi TSFunction ctermfg=Yellow ctermbg=NONE cterm=bold
    hi! link TSClass TSFunction
    hi TSMethod ctermfg=Gray ctermbg=NONE cterm=bold
    hi! link TSField TSMethod
    hi TSOperator ctermfg=Gray ctermbg=NONE cterm=bold
    hi TSLabel ctermfg=Gray ctermbg=NONE cterm=bold,italic
    hi! link TSRepeat TSLabel
    hi! link TSConditional TSLabel
    hi! link TSKeyword TSLabel
    hi! link TSKeywordOperator TSLabel
    hi! link TSVariableBuiltin TSLabel
    hi TSConstructor ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi! link TSPunctDelimeter Delimiter
    hi! link TSPunctBracket Delimiter
    hi pythonStatement ctermfg=Magenta ctermbg=NONE cterm=bold
    hi! link pythonRepeat pythonStatement
    hi! link pythonConditional pythonStatement
    hi! link pythonException pythonStatement
    hi pythonClass ctermfg=Yellow ctermbg=NONE cterm=bold
    hi! link pythonFunction pythonClass
    hi pythonOperator ctermfg=White ctermbg=NONE cterm=bold
    hi pythonTodo ctermfg=NONE ctermbg=Red cterm=bold
    hi! link htmlTag Constant
    hi! link htmlTagName htmlTag
    hi! link htmlEndTag htmlTag
    hi! link htmlSpecialTagName htmlTag
    hi! link gitcommitSummary Title
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
      hi markdownItalic cterm=NONE
      hi texItalStyle cterm=NONE
      hi TSLabel cterm=bold
    endif
    if has('nvim')
      hi! link TermCursor Cursor
      hi! link TermCursorNC CursorColumn
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'futon_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=Magenta ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi CursorLineNr ctermfg=Magenta ctermbg=Gray cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=Gray cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi LineNr ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor ctermfg=Black ctermbg=Magenta cterm=NONE
  hi Conceal ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Folded ctermfg=DarkGray ctermbg=Gray cterm=italic
  hi DiffAdd ctermfg=Green ctermbg=NONE cterm=reverse
  hi DiffChange ctermfg=Yellow ctermbg=NONE cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=NONE cterm=reverse
  hi DiffText ctermfg=Gray ctermbg=NONE cterm=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=Black cterm=reverse,undercurl
  hi! link ErrorMsg Error
  hi Warning ctermfg=Yellow ctermbg=NONE cterm=reverse,underline
  hi! link WarningMsg Warning
  hi IncSearch ctermfg=Gray ctermbg=NONE cterm=reverse
  hi MatchParen ctermfg=Black ctermbg=DarkGray cterm=underline
  hi Search ctermfg=Magenta ctermbg=NONE cterm=reverse
  hi Directory ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Question MoreMsg
  hi NonText ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Ignore NonText
  hi Pmenu ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi PmenuSbar ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Magenta cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Gray cterm=NONE
  hi WildMenu ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad ctermfg=Red ctermbg=Gray cterm=underline
  hi SpellCap ctermfg=Green ctermbg=Gray cterm=underline
  hi SpellLocal ctermfg=Blue ctermbg=Gray cterm=underline
  hi SpellRare ctermfg=Yellow ctermbg=Gray cterm=underline
  hi StatusLine ctermfg=Black ctermbg=NONE cterm=NONE
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title ctermfg=NONE ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=White ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Gray cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=Gray cterm=NONE
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special ctermfg=NONE ctermbg=NONE cterm=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment ctermfg=DarkGray ctermbg=NONE cterm=italic
  hi! link Whitespace Comment
  hi Identifier ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link Function Identifier
  hi PreProc ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Include PreProc
  hi Statement ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo ctermfg=Gray ctermbg=NONE cterm=bold
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=NONE cterm=reverse
  hi helpHyperTextJump ctermfg=Magenta ctermbg=NONE cterm=underline
  hi NormalMode ctermfg=Magenta ctermbg=NONE cterm=reverse
  hi InsertMode ctermfg=Green ctermbg=NONE cterm=reverse
  hi ReplaceMode ctermfg=Gray ctermbg=NONE cterm=reverse
  hi VisualMode ctermfg=Blue ctermbg=NONE cterm=reverse
  hi CommandMode ctermfg=Red ctermbg=NONE cterm=reverse
  hi! link NormalFloat Pmenu
  hi! link FloatBorder Normal
  hi NormalNC ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link Floaterm ColorColumn
  hi! link FloatermBorder Folded
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link markdownError Error
  hi texItalStyle ctermfg=NONE ctermbg=NONE cterm=italic
  hi! link LspDiagnosticsDefaultError Error
  hi! link LspDiagnosticsDefaultTextError Error
  hi! link LspDiagnosticsDefaultWarning Warning
  hi LspDiagnosticsDefaultInformation ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi LspDiagnosticsDefaultHint ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi LspDiagnosticsFloatingError ctermfg=Red ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingWarning ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingInformation ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi LspDiagnosticsFloatingHint ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextError ctermfg=Red ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextWarning ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextInformation ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi LspDiagnosticsVirtualTextHint ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi! link TSConstant Constant
  hi! link TSConstBuiltin Constant
  hi! link TSConstMacro Constant
  hi! link TSNumber Number
  hi! link TSFloat Float
  hi! link TSBoolean Boolean
  hi! link TSCharacter Character
  hi! link TSString String
  hi! link TSStringRegex String
  hi! link TSStringEscape String
  hi TSVariable ctermfg=Black ctermbg=NONE cterm=NONE
  hi TSFunction ctermfg=Yellow ctermbg=NONE cterm=bold
  hi! link TSClass TSFunction
  hi TSMethod ctermfg=DarkGray ctermbg=NONE cterm=bold
  hi! link TSField TSMethod
  hi TSOperator ctermfg=DarkGray ctermbg=NONE cterm=bold
  hi TSLabel ctermfg=DarkGray ctermbg=NONE cterm=bold,italic
  hi! link TSRepeat TSLabel
  hi! link TSConditional TSLabel
  hi! link TSKeyword TSLabel
  hi! link TSKeywordOperator TSLabel
  hi! link TSVariableBuiltin TSLabel
  hi TSConstructor ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi! link TSPunctDelimeter Delimiter
  hi! link TSPunctBracket Delimiter
  hi pythonStatement ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi! link pythonRepeat pythonStatement
  hi! link pythonConditional pythonStatement
  hi! link pythonException pythonStatement
  hi pythonClass ctermfg=Yellow ctermbg=NONE cterm=bold
  hi! link pythonFunction pythonClass
  hi pythonOperator ctermfg=Black ctermbg=NONE cterm=bold
  hi pythonTodo ctermfg=NONE ctermbg=Red cterm=bold
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi markdownItalic cterm=NONE
    hi texItalStyle cterm=NONE
    hi TSLabel cterm=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  if &background ==# 'dark'
    if get(g:, 'futon_transp_bg', 0)
      hi Normal term=NONE
      hi CursorLineNr term=NONE
      hi FoldColumn term=NONE
      hi Terminal term=NONE
    else
      hi Normal term=NONE
      hi CursorLineNr term=NONE
      hi FoldColumn term=NONE
      hi Terminal term=NONE
    endif
    hi LineNr term=NONE
    hi ColorColumn term=NONE
    hi! link CursorColumn ColorColumn
    hi! link CursorLine ColorColumn
    hi Cursor term=NONE
    hi Conceal term=NONE
    hi Folded term=italic
    hi DiffAdd term=reverse
    hi DiffChange term=reverse
    hi DiffDelete term=reverse
    hi DiffText term=bold,reverse
    hi! link diffAdded DiffAdd
    hi! link diffRemoved DiffDelete
    hi EndOfBuffer term=NONE
    hi Error term=reverse,undercurl
    hi! link ErrorMsg Error
    hi Warning term=reverse,underline
    hi! link WarningMsg Warning
    hi IncSearch term=reverse
    hi MatchParen term=underline
    hi Search term=reverse
    hi Directory term=NONE
    hi ModeMsg term=NONE
    hi MoreMsg term=NONE
    hi! link Question MoreMsg
    hi NonText term=NONE
    hi! link Ignore NonText
    hi Pmenu term=NONE
    hi PmenuSbar term=NONE
    hi PmenuSel term=NONE
    hi PmenuThumb term=NONE
    hi WildMenu term=NONE
    hi SignColumn term=NONE
    hi! link SpecialKey SignColumn
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi StatusLine term=NONE
    hi! link StatusLineNC Comment
    hi! link TabLine StatusLineNC
    hi! link TabLineFill StatusLineNC
    hi! link TabLineSel StatusLine
    hi Title term=bold
    hi VertSplit term=NONE
    hi Visual term=NONE
    hi VisualNOS term=NONE
    hi Constant term=NONE
    hi! link Boolean Constant
    hi! link Character Constant
    hi! link Number Constant
    hi! link Float Number
    hi! link String Constant
    hi Special term=bold
    hi! link SpecialChar Special
    hi! link SpecialComment Special
    hi! link Delimiter Special
    hi! link Debug Special
    hi Comment term=italic
    hi! link Whitespace Comment
    hi Identifier term=NONE
    hi! link Function Identifier
    hi PreProc term=NONE
    hi! link Include PreProc
    hi Statement term=NONE
    hi! link Label Statement
    hi! link Keyword Statement
    hi! link Operator Statement
    hi Type term=NONE
    hi! link StorageClass Type
    hi! link Structure Type
    hi Todo term=bold
    hi Underlined term=underline
    hi CursorIM term=reverse
    hi helpHyperTextJump term=underline
    hi NormalMode term=reverse
    hi InsertMode term=reverse
    hi ReplaceMode term=reverse
    hi VisualMode term=reverse
    hi CommandMode term=reverse
    hi! link NormalFloat Pmenu
    hi! link FloatBorder Normal
    hi NormalNC term=NONE
    hi! link Floaterm ColorColumn
    hi! link FloatermBorder Folded
    hi markdownBold term=bold
    hi markdownItalic term=italic
    hi! link markdownError Error
    hi texItalStyle term=italic
    hi! link LspDiagnosticsDefaultError Error
    hi! link LspDiagnosticsDefaultTextError Error
    hi! link LspDiagnosticsDefaultWarning Warning
    hi LspDiagnosticsDefaultInformation term=NONE
    hi LspDiagnosticsDefaultHint term=NONE
    hi LspDiagnosticsFloatingError term=NONE
    hi LspDiagnosticsFloatingWarning term=NONE
    hi LspDiagnosticsFloatingInformation term=NONE
    hi LspDiagnosticsFloatingHint term=NONE
    hi LspDiagnosticsVirtualTextError term=NONE
    hi LspDiagnosticsVirtualTextWarning term=NONE
    hi LspDiagnosticsVirtualTextInformation term=NONE
    hi LspDiagnosticsVirtualTextHint term=NONE
    hi! link TSConstant Constant
    hi! link TSConstBuiltin Constant
    hi! link TSConstMacro Constant
    hi! link TSNumber Number
    hi! link TSFloat Float
    hi! link TSBoolean Boolean
    hi! link TSCharacter Character
    hi! link TSString String
    hi! link TSStringRegex String
    hi! link TSStringEscape String
    hi TSVariable term=NONE
    hi TSFunction term=bold
    hi! link TSClass TSFunction
    hi TSMethod term=bold
    hi! link TSField TSMethod
    hi TSOperator term=bold
    hi TSLabel term=bold,italic
    hi! link TSRepeat TSLabel
    hi! link TSConditional TSLabel
    hi! link TSKeyword TSLabel
    hi! link TSKeywordOperator TSLabel
    hi! link TSVariableBuiltin TSLabel
    hi TSConstructor term=NONE
    hi! link TSPunctDelimeter Delimiter
    hi! link TSPunctBracket Delimiter
    hi pythonStatement term=bold
    hi! link pythonRepeat pythonStatement
    hi! link pythonConditional pythonStatement
    hi! link pythonException pythonStatement
    hi pythonClass term=bold
    hi! link pythonFunction pythonClass
    hi pythonOperator term=bold
    hi pythonTodo term=bold
    hi! link htmlTag Constant
    hi! link htmlTagName htmlTag
    hi! link htmlEndTag htmlTag
    hi! link htmlSpecialTagName htmlTag
    hi! link gitcommitSummary Title
    if !s:italics
      hi Folded term=NONE
      hi Comment term=NONE
      hi markdownItalic term=NONE
      hi texItalStyle term=NONE
      hi TSLabel term=bold
    endif
    if has('nvim')
      hi! link TermCursor Cursor
      hi! link TermCursorNC CursorColumn
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'futon_transp_bg', 0)
    hi Normal term=NONE
    hi CursorLineNr term=NONE
    hi FoldColumn term=NONE
    hi Terminal term=NONE
  else
    hi Normal term=NONE
    hi CursorLineNr term=NONE
    hi FoldColumn term=NONE
    hi Terminal term=NONE
  endif
  hi LineNr term=NONE
  hi ColorColumn term=NONE
  hi! link CursorColumn ColorColumn
  hi! link CursorLine ColorColumn
  hi Cursor term=NONE
  hi Conceal term=NONE
  hi Folded term=italic
  hi DiffAdd term=reverse
  hi DiffChange term=reverse
  hi DiffDelete term=reverse
  hi DiffText term=bold,reverse
  hi! link diffAdded DiffAdd
  hi! link diffRemoved DiffDelete
  hi EndOfBuffer term=NONE
  hi Error term=reverse,undercurl
  hi! link ErrorMsg Error
  hi Warning term=reverse,underline
  hi! link WarningMsg Warning
  hi IncSearch term=reverse
  hi MatchParen term=underline
  hi Search term=reverse
  hi Directory term=NONE
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi! link Question MoreMsg
  hi NonText term=NONE
  hi! link Ignore NonText
  hi Pmenu term=NONE
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi WildMenu term=NONE
  hi SignColumn term=NONE
  hi! link SpecialKey SignColumn
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=NONE
  hi! link StatusLineNC Comment
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi Title term=bold
  hi VertSplit term=NONE
  hi Visual term=NONE
  hi VisualNOS term=NONE
  hi Constant term=NONE
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Number Constant
  hi! link Float Number
  hi! link String Constant
  hi Special term=bold
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Delimiter Special
  hi! link Debug Special
  hi Comment term=italic
  hi! link Whitespace Comment
  hi Identifier term=NONE
  hi! link Function Identifier
  hi PreProc term=NONE
  hi! link Include PreProc
  hi Statement term=NONE
  hi! link Label Statement
  hi! link Keyword Statement
  hi! link Operator Statement
  hi Type term=NONE
  hi! link StorageClass Type
  hi! link Structure Type
  hi Todo term=bold
  hi Underlined term=underline
  hi CursorIM term=reverse
  hi helpHyperTextJump term=underline
  hi NormalMode term=reverse
  hi InsertMode term=reverse
  hi ReplaceMode term=reverse
  hi VisualMode term=reverse
  hi CommandMode term=reverse
  hi! link NormalFloat Pmenu
  hi! link FloatBorder Normal
  hi NormalNC term=NONE
  hi! link Floaterm ColorColumn
  hi! link FloatermBorder Folded
  hi markdownBold term=bold
  hi markdownItalic term=italic
  hi! link markdownError Error
  hi texItalStyle term=italic
  hi! link LspDiagnosticsDefaultError Error
  hi! link LspDiagnosticsDefaultTextError Error
  hi! link LspDiagnosticsDefaultWarning Warning
  hi LspDiagnosticsDefaultInformation term=NONE
  hi LspDiagnosticsDefaultHint term=NONE
  hi LspDiagnosticsFloatingError term=NONE
  hi LspDiagnosticsFloatingWarning term=NONE
  hi LspDiagnosticsFloatingInformation term=NONE
  hi LspDiagnosticsFloatingHint term=NONE
  hi LspDiagnosticsVirtualTextError term=NONE
  hi LspDiagnosticsVirtualTextWarning term=NONE
  hi LspDiagnosticsVirtualTextInformation term=NONE
  hi LspDiagnosticsVirtualTextHint term=NONE
  hi! link TSConstant Constant
  hi! link TSConstBuiltin Constant
  hi! link TSConstMacro Constant
  hi! link TSNumber Number
  hi! link TSFloat Float
  hi! link TSBoolean Boolean
  hi! link TSCharacter Character
  hi! link TSString String
  hi! link TSStringRegex String
  hi! link TSStringEscape String
  hi TSVariable term=NONE
  hi TSFunction term=bold
  hi! link TSClass TSFunction
  hi TSMethod term=bold
  hi! link TSField TSMethod
  hi TSOperator term=bold
  hi TSLabel term=bold,italic
  hi! link TSRepeat TSLabel
  hi! link TSConditional TSLabel
  hi! link TSKeyword TSLabel
  hi! link TSKeywordOperator TSLabel
  hi! link TSVariableBuiltin TSLabel
  hi TSConstructor term=NONE
  hi! link TSPunctDelimeter Delimiter
  hi! link TSPunctBracket Delimiter
  hi pythonStatement term=bold
  hi! link pythonRepeat pythonStatement
  hi! link pythonConditional pythonStatement
  hi! link pythonException pythonStatement
  hi pythonClass term=bold
  hi! link pythonFunction pythonClass
  hi pythonOperator term=bold
  hi pythonTodo term=bold
  hi! link htmlTag Constant
  hi! link htmlTagName htmlTag
  hi! link htmlEndTag htmlTag
  hi! link htmlSpecialTagName htmlTag
  hi! link gitcommitSummary Title
  if !s:italics
    hi Folded term=NONE
    hi Comment term=NONE
    hi markdownItalic term=NONE
    hi texItalStyle term=NONE
    hi TSLabel term=bold
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi! link TermCursorNC CursorColumn
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: grey        #767676 ~ DarkGray
" Color: accent      #9b73a8 ~ Magenta
" Color: xdaccent      #82598f ~ DarkMagenta
" Color: xlaccent      #b192bc ~ Magenta
" Color: red        #cc3033 ~ Red
" Color: green      #7c981f ~ Green
" Color: yellow     #d79921 ~ Yellow
" Color: blue       #5585a8 ~ Blue
" Color: magenta    #9b73a8 ~ Magenta
" Color: cyan       #59a6a6 ~ Cyan
" Color: orange     #d65d0e ~ Gray
" Color: xdred        #a32629 ~ DarkRed
" Color: xdgreen      #596e16 ~ DarkGreen
" Color: xdyellow     #ab7a1a ~ DarkYellow
" Color: xdblue       #446a86 ~ DarkBlue
" Color: xdmagenta    #82598f ~ DarkMagenta
" Color: xdcyan       #478585 ~ DarkCyan
" Color: xdorange     #a6480b ~ Gray
" Color: xlred        #d8575a ~ Red
" Color: xlgreen      #9fc228 ~ Green
" Color: xlyellow     #e3ae48 ~ Yellow
" Color: xlblue       #769dba ~ Blue
" Color: xlmagenta    #b192bc ~ Magenta
" Color: xlcyan       #7ab8b8 ~ Cyan
" Color: xlorange     #f17626 ~ DarkGray
" Color: bkgrd_0 #1c1c1c ~ Black
" Color: bkgrd_1 #2e2e2e ~ DarkGray
" Color: bkgrd_2 #404040 ~ DarkGray
" Color: bkgrd_3 #525252 ~ DarkGray
" Color: bkgrd_4 #646464 ~ DarkGray
" Color: frgrd_0 #eeeeee ~ White
" Color: frgrd_1 #d6d6d6 ~ Gray
" Color: frgrd_2 #bebebe ~ Gray
" Color: frgrd_3 #a6a6a6 ~ Gray
" Color: frgrd_4 #8e8e8e ~ Gray
" Term Colors: bkgrd_0 red green yellow blue magenta cyan frgrd_2
" Term Colors: bkgrd_2 xlred xlgreen xlyellow xlblue xlmagenta xlcyan frgrd_0
" Background: light
" Color: grey        #767676 ~ DarkGray
" Color: accent      #9b73a8 ~ Magenta
" Color: xdaccent      #b192bc ~ Magenta
" Color: xlaccent      #82598f ~ DarkMagenta
" Color: red        #cc3033 ~ Red
" Color: green      #7c981f ~ Green
" Color: yellow     #d79921 ~ Yellow
" Color: blue       #5585a8 ~ Blue
" Color: magenta    #9b73a8 ~ Magenta
" Color: cyan       #59a6a6 ~ Cyan
" Color: orange     #d65d0e ~ Gray
" Color: xdred        #d8575a ~ DarkRed
" Color: xdgreen      #9fc228 ~ DarkGreen
" Color: xdyellow     #e3ae48 ~ DarkYellow
" Color: xdblue       #769dba ~ DarkBlue
" Color: xdmagenta    #b192bc ~ DarkMagenta
" Color: xdcyan       #7ab8b8 ~ DarkCyan
" Color: xdorange     #f17626 ~ DarkGray
" Color: xlred        #a32629 ~ Red
" Color: xlgreen      #596e16 ~ Green
" Color: xlyellow     #ab7a1a ~ Yellow
" Color: xlblue       #446a86 ~ Blue
" Color: xlmagenta    #82598f ~ Magenta
" Color: xlcyan       #478585 ~ Cyan
" Color: xlorange     #a6480b ~ Gray
" Color: bkgrd_0 #eeeeee ~ White
" Color: bkgrd_1 #d6d6d6 ~ Gray
" Color: bkgrd_2 #bebebe ~ Gray
" Color: bkgrd_3 #a6a6a6 ~ Gray
" Color: bkgrd_4 #8e8e8e ~ Gray
" Color: frgrd_0 #1c1c1c ~ Black
" Color: frgrd_1 #2e2e2e ~ DarkGray
" Color: frgrd_2 #404040 ~ DarkGray
" Color: frgrd_3 #525252 ~ DarkGray
" Color: frgrd_4 #646464 ~ DarkGray
" Term Colors: bkgrd_0 red green yellow blue magenta orange frgrd_2
" Term Colors: bkgrd_2 xdred xdgreen xdyellow xdblue xdmagenta xdcyan frgrd_0
" Background: any
" vim: et ts=2 sw=2
